In [1]:
import torch
from PIL import Image
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import transforms,datasets,models,utils

In [2]:
#自定义池化层
class AdaptiveConcatPool2d(nn.Module):
    def __init__(self,size = None):
        super(AdaptiveConcatPool2d,self).__init__()
        size = size or (1,1) #kernel大小
        #自适应算法能够自动计算核的大小和每次移动的步长
        self.avgPooling = nn.AdaptiveAvgPool2d(size) #自适应平均池化
        self.maxPooling = nn.AdaptiveMaxPool2d(size) #自适应最大池化
    def forward(self,x): #前向传播
        #拼接avg和max
        return torch.cat([self.maxPooling(x),self.avgPooling(x)],dim = 1) #纵向拼接

In [3]:
img_path = 'E:/大三下/计算机视觉/大作业/val'
image_transforms = {
        'valid': transforms.Compose([
                    transforms.Resize(300),
                    transforms.CenterCrop(256),
                    transforms.ToTensor(),
                    transforms.Normalize([0.485,0.456,0.406],
                                         [0.229,0.224,0.225])
                ])
    }

In [4]:
datasets = {
    'valid': datasets.ImageFolder(img_path,transform = image_transforms['valid'])
}
dataloaders = {
    'valid': DataLoader(datasets['valid'])
}


In [5]:
model = torch.load('model_new.pth',map_location = torch.device('cpu'))
model.eval()
print("load finished!")

load finished!


In [6]:
with torch.no_grad():
    for batch_id,(images,labels) in enumerate(dataloaders['valid']):
        outputs = model(images)
        _,predicted = torch.max(outputs,dim = 1)
        print(predicted)

tensor([0])
tensor([7])
tensor([7])
tensor([7])
tensor([7])
tensor([7])
tensor([6])
tensor([6])
tensor([6])
tensor([6])
tensor([6])
tensor([0])
tensor([4])
tensor([4])
tensor([4])
tensor([4])
tensor([4])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([5])
tensor([2])
tensor([2])
tensor([2])
tensor([2])
tensor([2])
tensor([3])
tensor([3])
tensor([3])
tensor([3])
tensor([3])
